config/routes.rb
EnokiLog::Application.routes.draw do
  resources :users
  resources :subjects, only: [:new, :create, :destroy, :edit, :update, :show]
  resources :materials, only: [:create, :destroy]
  resources :comments,  only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',        to: 'users#new',            via: 'get'
  match '/profile',       to: 'users#edit',           via: 'get'
  match '/mypage',        to: 'users#show',           via: 'get'
  match '/signin',        to: 'sessions#new',         via: 'get'
  match '/signout',       to: 'sessions#destroy',     via: 'delete'
  match '/about',         to: 'static_pages#about',   via: 'get'
  match '/share/:url',    to: 'subjects#show',        via: 'get'
  match '/manage/:url',   to: 'subjects#edit',        via: 'get'
  match '/log/:url',      to: 'subjects#log',         via: 'get'
  get 'users/:id/resign', to: 'users#resign',          as: 'resign'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :subjects, dependent: :destroy
	before_save { email.downcase! }
	before_create :create_remember_token

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, 
										format: { with: VALID_EMAIL_REGEX }, 
										uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user,  only: [:show, :edit, :update, :resign, :destroy]
	before_action :correct_user,    only: [:update, :resign, :destroy]
	before_action :set_user,        only: [:show, :edit]
	before_action :signed_out_user, only: [:new, :create]
	
	def index
		render 'show'
	end

	def show
		@subjects = @user.subjects.paginate(page: params[:page], :per_page => 5)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to Enoki Log!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
	end

	def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
	end

	def resign
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User destroyed."
		redirect_to(signup_url)
	end

	private

		def user_params
			params.require(:user).permit(:email, :password, :password_confirmation)
		end

		# Before actions
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def set_user
    	@user = current_user
    	redirect_to(root_path) if @user.blank?
    end

end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-large btn-success" %>
    <% end %>
    <p>登録情報や投稿内容は<%= link_to "アカウント削除", resign_path(current_user) %>すると消えます。</p>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
	    <%= render 'fields', f: f %>
	    <%= f.submit "Create my account", class: "btn btn-large btn-success" %>
	  <% end %>
	</div>
</div>

app/views/users/resign.html.erb
<% provide(:title, "Resign") %>
<h1>アカウント削除</h1>
<div class="row">
	<div class="span6 offset3">
		<h2>１度削除したら二度と復元できません。</h2>
	</div>
</div>
<div class="row">
	<div class="span2 offset4">
		<%= link_to "削除する", @user, method: :delete, data: { confirm: "本当に削除しますか?" }, class: "btn btn-large btn-danger" %>
	</div>
	<div class="span2">
		<%= link_to "キャンセル", current_user, class: "btn btn-large" %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, "MyPage") %>
<div class="row">
	<aside class="span4">
		<section>
      <h1>Your Account</h1>
			<div><%= @user.email %></div>
      <span class="before-button"></span>
			<%= link_to "新しい学習を記録する", "/subjects/new", class: "btn btn-large btn-success" %>
		</section>
	</aside>
	<div class="span8">
    <% if @user.subjects.any? %>
      <h3>あなたの学習記録 (<%= @user.subjects.count %>)</h3>
      <ol class="subjects">
        <%= render @subjects %>
      </ol>
      <%= will_paginate @subjects %>
    <% else %>
    	<h3>まだ学習の記録はありません</h3> 
    	<span>新しい学びの記録を始めてみましょう！</span>
    <% end %>
  </div>
</div>