config/routes.rb
EnokiLog::Application.routes.draw do
  resources :users
  resources :subjects, only: [:new, :create, :destroy, :edit, :update, :show]
  resources :materials, only: [:create, :destroy]
  resources :comments,  only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',        to: 'users#new',            via: 'get'
  match '/profile',       to: 'users#edit',           via: 'get'
  match '/mypage',        to: 'users#show',           via: 'get'
  match '/signin',        to: 'sessions#new',         via: 'get'
  match '/signout',       to: 'sessions#destroy',     via: 'delete'
  match '/about',         to: 'static_pages#about',   via: 'get'
  match '/share/:url',    to: 'subjects#show',        via: 'get'
  match '/manage/:url',   to: 'subjects#edit',        via: 'get'
  match '/log/:url',      to: 'subjects#log',         via: 'get'
  get 'users/:id/resign', to: 'users#resign',          as: 'resign'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <%= link_to "» Enoki Log についてもっと知る", about_path %>
  <small>
    &copy; 2014 Enoki Log.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
    <div class="container">
      <%= link_to root_path, id: "logo" do %>
        <span class="fa fa-tree"></span> Enoki Log
      <% end %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Study List", mypage_path %></li>
                <li><%= link_to "Settings", profile_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
  <div class="container" id="main">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
		<%= yield %>
  </div>
  <div class="container">
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<%= yield %>
  <div class="container">
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>